### ISSUE TITLE
ESP32 WiFi integration 

### ISSUE THREAD

**Issue by luc-github** [simon-jouet/Marlin#7]
when including `<WiFi.h>` there is a conflict with min / max functions which are macro in ESP32

```
#ifndef _GLIBCXX_VECTOR
// arduino is not compatible with std::vector
#define min(a,b) ((a)<(b)?(a):(b))
#define max(a,b) ((a)>(b)?(a):(b))
#endif

#define _min(a,b) ((a)<(b)?(a):(b))
#define _max(a,b) ((a)>(b)?(a):(b))
```
Using _min and _max seems solving the issue

**Comment by luc-github** [comment]
using : 
```
// Enable hooks into idle and setup for Wifi management
#define HAL_IDLETASK 1
#define HAL_INIT 1
``` 
In HAL_ESP32.h

and
```
#include "esp3d.h"
Esp3D myesp3d;
void HAL_idletask(void) { 
myesp3d.process();
}

void HAL_init(void) { 
 myesp3d.begin();
}
```
In HAL_ESP32.cpp

And the compilation is fine without renaming min/max to _min/_max

**Comment by simon-jouet** [comment]
Closing this :) the latest push is working okay with OTA enabled (well OTA sometimes fail but it works the majority of the time)
